"""Fine-tune DistilBERT on arXiv primary categories.

Run once, on Colab (see training/colab.md). Committed for provenance; never
part of the runtime image.

    python training/train.py             # train, save locally, push to the Hub
    python training/train.py --no-push   # local only
    python training/train.py --inspect   # print the dataset schema and exit
"""

import argparse
import inspect
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from datasets import load_dataset
from sklearn.metrics import confusion_matrix, f1_score
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    Trainer,
    TrainingArguments,
)

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))
from serving.preprocessing import MAX_INPUT_CHARS, MAX_TOKENS, join  # noqa: E402

DATASET = "TimSchopf/arxiv_categories"
BASE = "distilbert-base-uncased"
HUB_REPO_NAME = "arxiv-classifier-v1"   # namespace comes from the token's account
OUT = REPO / "models" / "arxiv-v1"
DOCS = REPO / "docs"
VERSION = "v1.0.0"
SEED = 42

# ~40k rows, keeping the dataset's own 80/10/10 proportions.
N = {"train": 32_000, "validation": 4_000, "test": 4_000}

# cs.LG / cs.AI / stat.ML overlap heavily and are kept in deliberately: the
# accuracy ceiling is in the labels, not the model.
LABELS = ["cs.LG", "cs.CV", "cs.CL", "cs.AI", "cs.RO",
          "cs.CR", "cs.SE", "cs.DS", "cs.NI", "stat.ML"]
LABEL2ID = {name: i for i, name in enumerate(LABELS)}


def primary(categories: list[str]) -> str:
    """arXiv lists the primary category first. Rows look like
    'Computer Science Archive->cs.CV', so take the leaf."""
    return categories[0].split("->")[-1]


def prepare(split: str, tokenizer):
    ds = load_dataset(DATASET, split=split)
    ds = ds.filter(lambda r: primary(r["categories"]) in LABEL2ID)
    ds = ds.shuffle(seed=SEED).select(range(min(N[split], len(ds))))

    def encode(batch):
        enc = tokenizer(
            [join(t, a) for t, a in zip(batch["title"], batch["abstract"])],
            truncation=True,
            max_length=MAX_TOKENS,
        )
        enc["labels"] = [LABEL2ID[primary(c)] for c in batch["categories"]]
        return enc

    return ds.map(encode, batched=True, remove_columns=ds.column_names)


def score(logits: np.ndarray, y: np.ndarray) -> dict:
    order = np.argsort(-logits, axis=1)
    top1 = order[:, 0]
    return {
        "top1_accuracy": round(float((top1 == y).mean()), 4),
        "top3_accuracy": round(float((order[:, :3] == y[:, None]).any(1).mean()), 4),
        "macro_f1": round(float(f1_score(y, top1, average="macro")), 4),
    }


def write_eval_docs(logits: np.ndarray, y: np.ndarray, metrics: dict) -> None:
    """Confusion matrix + metrics land in docs/ because models/ is gitignored."""
    DOCS.mkdir(exist_ok=True)
    cm = confusion_matrix(y, logits.argmax(1), labels=range(len(LABELS)))

    fig, ax = plt.subplots(figsize=(7.5, 6.5))
    ax.imshow(cm / cm.sum(1, keepdims=True), cmap="Blues", vmin=0, vmax=1)
    ax.set(xticks=range(len(LABELS)), yticks=range(len(LABELS)),
           xlabel="predicted", ylabel="true", title="arXiv category confusion (row-normalised)")
    ax.set_xticklabels(LABELS, rotation=45, ha="right")
    ax.set_yticklabels(LABELS)
    for i in range(len(LABELS)):
        for j in range(len(LABELS)):
            ax.text(j, i, cm[i, j], ha="center", va="center", fontsize=7)
    fig.tight_layout()
    fig.savefig(DOCS / "confusion_matrix.png", dpi=150)

    header = "| true \\ pred | " + " | ".join(LABELS) + " |"
    rows = "\n".join(
        f"| **{LABELS[i]}** | " + " | ".join(str(v) for v in cm[i]) + " |"
        for i in range(len(LABELS))
    )
    (DOCS / "model_eval.md").write_text(
        f"""# Model evaluation — {VERSION}

Held-out test split, {len(y)} papers. Generated by `training/train.py`.

| metric | value |
|---|---|
| top-1 accuracy | {metrics['top1_accuracy']} |
| top-3 accuracy | {metrics['top3_accuracy']} |
| macro F1 | {metrics['macro_f1']} |

![confusion matrix](confusion_matrix.png)

{header}
|{'---|' * (len(LABELS) + 1)}
{rows}
"""
    )


def training_args(**kw) -> TrainingArguments:
    """transformers v5 dropped several TrainingArguments fields (warmup_ratio
    among them). Keep whatever this install accepts and say what was dropped,
    rather than pinning a version we can't test from here."""
    valid = inspect.signature(TrainingArguments.__init__).parameters
    dropped = {k: v for k, v in kw.items() if k not in valid}
    if dropped:
        print(f"[train] TrainingArguments does not accept, ignoring: {dropped}")
    return TrainingArguments(**{k: v for k, v in kw.items() if k in valid})


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-push", action="store_true")
    ap.add_argument("--inspect", action="store_true")
    args = ap.parse_args()

    if args.inspect:
        ds = load_dataset(DATASET)
        print(ds)
        print(json.dumps(ds["train"][0], indent=2, default=str))
        return

    # Prove we can write to the Hub before spending the GPU time, not after.
    api = repo = None
    if not args.no_push:
        from huggingface_hub import HfApi

        api = HfApi()
        try:
            repo = f"{api.whoami()['name']}/{HUB_REPO_NAME}"
            api.create_repo(repo, repo_type="model", exist_ok=True)
        except Exception as e:
            raise SystemExit(
                f"Hub write check failed ({e}).\n"
                "Set HF_TOKEN to a *write* token, or pass --no-push."
            )
        print(f"[train] will push to {repo}")

    tokenizer = AutoTokenizer.from_pretrained(BASE)
    splits = {s: prepare(s, tokenizer) for s in N}
    print({s: len(d) for s, d in splits.items()})

    model = AutoModelForSequenceClassification.from_pretrained(
        BASE,
        num_labels=len(LABELS),
        id2label=dict(enumerate(LABELS)),
        label2id=LABEL2ID,
    )

    trainer = Trainer(
        model=model,
        args=training_args(
            output_dir="/tmp/arxiv-train",
            num_train_epochs=2,
            per_device_train_batch_size=32,
            per_device_eval_batch_size=64,
            learning_rate=5e-5,
            warmup_ratio=0.06,
            fp16=True,
            logging_steps=100,
            save_strategy="no",
            report_to="none",
            seed=SEED,
        ),
        train_dataset=splits["train"],
        eval_dataset=splits["validation"],
        data_collator=DataCollatorWithPadding(tokenizer),
    )
    trainer.train()

    out = trainer.predict(splits["test"])
    metrics = score(out.predictions, out.label_ids)
    print(metrics)
    write_eval_docs(out.predictions, out.label_ids, metrics)

    OUT.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(OUT)
    tokenizer.save_pretrained(OUT)
    (OUT / "model_card.json").write_text(json.dumps({
        "name": "arxiv-category-classifier",
        "version": VERSION,
        "base_model": BASE,
        "trained_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "dataset": f"{DATASET} (cs subset, {sum(len(d) for d in splits.values())})",
        "labels": LABELS,
        "input_format": 'title + "\\n\\n" + abstract',
        "max_input_chars": MAX_INPUT_CHARS,
        "max_tokens": MAX_TOKENS,
        "metrics": metrics,
    }, indent=2) + "\n")
    print(f"saved to {OUT}")

    if args.no_push:
        return
    info = api.upload_folder(
        folder_path=str(OUT), repo_id=repo,
        commit_message=f"arxiv-category-classifier {VERSION}",
    )
    print(f"pushed to {repo}")
    print(f"\nHub revision — pin this as the Dockerfile ARG (M4):\n  {info.oid}\n")


if __name__ == "__main__":
    main()
